"""requests conversations and price proposals

Revision ID: c75a01d29f10
Revises: b62f3d910ea4
Create Date: 2026-10-02 11:53:35.050404
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c75a01d29f10"
down_revision: str | None = "b62f3d910ea4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "booking_requests",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("master_id", sa.Uuid(), nullable=False),
        sa.Column("client_user_id", sa.Uuid(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("service_name_snapshot", sa.String(length=160), nullable=False),
        sa.Column("client_name_snapshot", sa.String(length=160), nullable=False),
        sa.Column("client_phone_snapshot", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'waiting_master', 'waiting_client', 'terms_proposed', "
            "'terms_accepted', 'booked', 'cancelled', 'closed')",
            name=op.f("ck_booking_requests_status"),
        ),
        sa.CheckConstraint(
            "length(description) BETWEEN 1 AND 4000",
            name=op.f("ck_booking_requests_description_length"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_booking_requests_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["client_user_id"],
            ["telegram_users.id"],
            name=op.f("fk_booking_requests_client_user_id_telegram_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["master_id"],
            ["masters.id"],
            name=op.f("fk_booking_requests_master_id_masters"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_booking_requests_service_id_services"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_booking_requests")),
    )
    op.create_index(
        "ix_booking_requests_business_status_created",
        "booking_requests",
        ["business_id", "status", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_booking_requests_client_created",
        "booking_requests",
        ["client_user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_booking_requests_master_created",
        "booking_requests",
        ["master_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "conversations",
        sa.Column("booking_request_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("last_message_sequence", sa.Integer(), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('open', 'closed')", name=op.f("ck_conversations_status")),
        sa.CheckConstraint(
            "last_message_sequence >= 0", name=op.f("ck_conversations_sequence_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["booking_request_id"],
            ["booking_requests.id"],
            name=op.f("fk_conversations_booking_request_id_booking_requests"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        sa.UniqueConstraint("booking_request_id", name=op.f("uq_conversations_booking_request_id")),
    )
    op.create_table(
        "price_proposals",
        sa.Column("booking_request_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f("ck_price_proposals_currency")),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'rejected', 'superseded')",
            name=op.f("ck_price_proposals_status"),
        ),
        sa.CheckConstraint(
            "amount_minor BETWEEN 0 AND 2000000000", name=op.f("ck_price_proposals_amount")
        ),
        sa.CheckConstraint(
            "comment IS NULL OR length(comment) <= 2000",
            name=op.f("ck_price_proposals_comment_length"),
        ),
        sa.CheckConstraint("revision > 0", name=op.f("ck_price_proposals_revision")),
        sa.ForeignKeyConstraint(
            ["booking_request_id"],
            ["booking_requests.id"],
            name=op.f("fk_price_proposals_booking_request_id_booking_requests"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["telegram_users.id"],
            name=op.f("fk_price_proposals_created_by_user_id_telegram_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_proposals")),
        sa.UniqueConstraint(
            "booking_request_id", "revision", name=op.f("uq_price_proposals_booking_request_id")
        ),
    )
    op.create_index(
        "ix_price_proposals_request_status",
        "price_proposals",
        ["booking_request_id", "status"],
        unique=False,
    )
    op.create_index(
        "uq_price_proposals_pending",
        "price_proposals",
        ["booking_request_id"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "conversation_messages",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("sender_user_id", sa.Uuid(), nullable=True),
        sa.Column("sender_role", sa.String(length=24), nullable=False),
        sa.Column("message_type", sa.String(length=24), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("telegram_file_id", sa.String(length=512), nullable=True),
        sa.Column("telegram_file_unique_id", sa.String(length=256), nullable=True),
        sa.Column("event_type", sa.String(length=100), nullable=True),
        sa.Column("event_payload", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(message_type = 'system' AND sender_role = 'system' AND event_type IS NOT NULL "
            "AND event_payload IS NOT NULL AND telegram_file_id IS NULL) OR "
            "(message_type != 'system' AND sender_role != 'system' AND sender_user_id IS NOT NULL "
            "AND event_type IS NULL AND event_payload IS NULL AND "
            "((message_type = 'text' AND text IS NOT NULL AND length(text) > 0 "
            "AND telegram_file_id IS NULL AND telegram_file_unique_id IS NULL) OR "
            "(message_type IN ('photo', 'document') AND telegram_file_id IS NOT NULL "
            "AND telegram_file_unique_id IS NOT NULL)))",
            name=op.f("ck_conversation_messages_content"),
        ),
        sa.CheckConstraint(
            "message_type IN ('text', 'photo', 'document', 'system')",
            name=op.f("ck_conversation_messages_type"),
        ),
        sa.CheckConstraint(
            "sender_role IN ('client', 'master', 'system')",
            name=op.f("ck_conversation_messages_sender_role"),
        ),
        sa.CheckConstraint("sequence > 0", name=op.f("ck_conversation_messages_sequence_positive")),
        sa.CheckConstraint(
            "text IS NULL OR length(text) <= 4000",
            name=op.f("ck_conversation_messages_text_length"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_conversation_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sender_user_id"],
            ["telegram_users.id"],
            name=op.f("fk_conversation_messages_sender_user_id_telegram_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversation_messages")),
        sa.UniqueConstraint(
            "conversation_id", "sequence", name=op.f("uq_conversation_messages_conversation_id")
        ),
    )
    op.create_index(
        "ix_conversation_messages_conversation_created",
        "conversation_messages",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "conversation_read_states",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("last_read_sequence", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "last_read_sequence >= 0", name=op.f("ck_conversation_read_states_sequence_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_conversation_read_states_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["telegram_users.id"],
            name=op.f("fk_conversation_read_states_user_id_telegram_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "conversation_id", "user_id", name=op.f("pk_conversation_read_states")
        ),
    )
    op.add_column("appointments", sa.Column("booking_request_id", sa.Uuid(), nullable=True))
    op.create_unique_constraint(
        op.f("uq_appointments_booking_request_id"), "appointments", ["booking_request_id"]
    )
    op.create_foreign_key(
        op.f("fk_appointments_booking_request_id_booking_requests"),
        "appointments",
        "booking_requests",
        ["booking_request_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.add_column("notification_jobs", sa.Column("booking_request_id", sa.Uuid(), nullable=True))
    op.add_column("notification_jobs", sa.Column("event_key", sa.String(length=160), nullable=True))
    op.create_index(
        op.f("ix_notification_jobs_booking_request_id"),
        "notification_jobs",
        ["booking_request_id"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("uq_notification_jobs_event_key"), "notification_jobs", ["event_key"]
    )
    op.create_foreign_key(
        op.f("fk_notification_jobs_booking_request_id_booking_requests"),
        "notification_jobs",
        "booking_requests",
        ["booking_request_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "services",
        sa.Column("pricing_mode", sa.String(length=24), server_default="fixed", nullable=False),
    )
    op.create_check_constraint(
        op.f("ck_services_pricing_mode"),
        "services",
        "pricing_mode IN ('fixed', 'from', 'negotiable')",
    )
    # Messages and commercial terms are append-only, even if a future caller uses raw SQL.
    op.execute("""
        CREATE FUNCTION protect_conversation_message() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'Conversation messages are immutable';
        END $$
    """)
    op.execute("""
        CREATE TRIGGER conversation_message_immutable BEFORE UPDATE ON conversation_messages
        FOR EACH ROW EXECUTE FUNCTION protect_conversation_message()
    """)
    op.execute("""
        CREATE FUNCTION protect_price_proposal() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF ROW(NEW.id, NEW.booking_request_id, NEW.created_by_user_id, NEW.revision,
                   NEW.amount_minor, NEW.currency, NEW.comment, NEW.created_at)
               IS DISTINCT FROM
               ROW(OLD.id, OLD.booking_request_id, OLD.created_by_user_id, OLD.revision,
                   OLD.amount_minor, OLD.currency, OLD.comment, OLD.created_at)
            THEN RAISE EXCEPTION 'Price proposal terms are immutable'; END IF;
            IF OLD.status != 'pending' AND NEW IS DISTINCT FROM OLD
            THEN RAISE EXCEPTION 'Resolved price proposals are immutable'; END IF;
            RETURN NEW;
        END $$
    """)
    op.execute("""
        CREATE TRIGGER price_proposal_immutable BEFORE UPDATE ON price_proposals
        FOR EACH ROW EXECUTE FUNCTION protect_price_proposal()
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # Downgrading a populated deployment would discard commercial history.
    op.execute("""
        DO $$ BEGIN
            IF EXISTS (SELECT 1 FROM booking_requests) THEN
                RAISE EXCEPTION 'Cannot downgrade: preserve request/conversation history';
            END IF;
        END $$
    """)
    op.execute("DROP TRIGGER conversation_message_immutable ON conversation_messages")
    op.execute("DROP FUNCTION protect_conversation_message()")
    op.execute("DROP TRIGGER price_proposal_immutable ON price_proposals")
    op.execute("DROP FUNCTION protect_price_proposal()")
    op.drop_constraint(op.f("ck_services_pricing_mode"), "services", type_="check")
    op.drop_column("services", "pricing_mode")
    op.drop_constraint(
        op.f("fk_notification_jobs_booking_request_id_booking_requests"),
        "notification_jobs",
        type_="foreignkey",
    )
    op.drop_constraint(op.f("uq_notification_jobs_event_key"), "notification_jobs", type_="unique")
    op.drop_index(op.f("ix_notification_jobs_booking_request_id"), table_name="notification_jobs")
    op.drop_column("notification_jobs", "event_key")
    op.drop_column("notification_jobs", "booking_request_id")
    op.drop_constraint(
        op.f("fk_appointments_booking_request_id_booking_requests"),
        "appointments",
        type_="foreignkey",
    )
    op.drop_constraint(op.f("uq_appointments_booking_request_id"), "appointments", type_="unique")
    op.drop_column("appointments", "booking_request_id")
    op.drop_table("conversation_read_states")
    op.drop_index(
        "ix_conversation_messages_conversation_created", table_name="conversation_messages"
    )
    op.drop_table("conversation_messages")
    op.drop_index(
        "uq_price_proposals_pending",
        table_name="price_proposals",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index("ix_price_proposals_request_status", table_name="price_proposals")
    op.drop_table("price_proposals")
    op.drop_table("conversations")
    op.drop_index("ix_booking_requests_master_created", table_name="booking_requests")
    op.drop_index("ix_booking_requests_client_created", table_name="booking_requests")
    op.drop_index("ix_booking_requests_business_status_created", table_name="booking_requests")
    op.drop_table("booking_requests")
    # ### end Alembic commands ###
